
let FeedbackTypes = {
    NONE: "NONE",
    CONFIRM_ONLY: "CONFIRM_ONLY",
    BINARY: "BINARY",
    BINARY_POINTS: "BINARY_POINTS",
    QUIZ: "QUIZ",
    POINTS: "POINTS",
    NER: "NER",
    CLASSIFICATION: "CLASSIFICATION",
    QUESTIONNAIRE: "QUESTIONNAIRE",
    REGRESSION: "REGRESSION"
};


export default FeedbackTypes;
